GET http://localhost:3000/articles?title=malo
Authorization: Bearer 123456

###

POST http://localhost:3000/articles/new
Content-Type: application/json

{
    "title" : "mALO",
    "markdown": "#Javascript Arrays",
    "tags": "['hola','perro]"
}

###
DELETE http://localhost:3000/articles/delete/63474771a7df3dffe0b804a1

###
PUT http://localhost:3000/articles/edit/6347478ea7df3dffe0b804a7
Content-Type: application/json

{
    "title" : "Titulo Cambiado",
    "markdown": "#c++",
    "tags": "['XD','perro]"
}


